language: java

sudo: false

install: true

jdk:
  - oraclejdk8
  - oraclejdk9
  - jdk8
  - jdk9

script: ant build

notifications:
  email:
    recipients:
      uncledeni@mail.ru
    on_success: never
    on_failure: always