language: java

sudo: false

install: true

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

notifications:
  email:
    recipients:
      uncledeni@mail.ru
    on_success: never
    on_failure: always